#!/bin/bash
echo;
echo "Set fastest mirror for DNF";
echo;
echo 'fastestmirror=1' | sudo tee -a /etc/dnf/dnf.conf && echo 'max_parallel_downloads=10' | sudo tee -a /etc/dnf/dnf.conf && echo 'deltarpm=true' | sudo tee -a /etc/dnf/dnf.conf && sudo dnf update -yq && sudo dnf autoremove -yq ;
echo;
echo "Installing needed groups...";
echo;
sudo dnf group install "Common NetworkManager Submodules" "Standard" "Printing Support" "Core" "Hardware Support" "Administration Tools" "System Tools" "C Development Tools and Libraries" "Development Tools" "Sound and Video" -yq;
echo;
echo "Enable Needed Repos";
sudo dnf install -y --nogpgcheck --repofrompath 'terra,https://repos/fyralabs/terra$releasever' terra-release;
sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm;
sudo dnf update --refresh -yq;
echo;
echo "Install the needed applications";
echo;
sudo dnf install sddm niri niri-settings noctalia-shell mate-polkit qt6ct qt5ct flatpak network-manager-applet papirus-icon-theme kde-connect vim gvim alactritty fuzzel brightnessctl python3 gnome-keyring wdisplays swaylock seahorse pluma pluma-plugins novelwriter intel-undervolt stress-ng imagemagick pipewire pipewire-pulseaudio pipewire-alsa wireplumber alsa-sof-firmware cups-pk-helper pcmanfm xwayland-satellite wlr-randr fastfetch xdg-desktop-portal -y --skip-broken;
echo;
echo "Install browser";
echo;
curl -fsS https://dl.brave.com/install.sh | sh;
echo;
echo "Installing hblock";
echo;
curl -o /tmp/hblock 'https://raw.githubusercontent.com/hectorm/hblock/v3.3.2/hblock' && echo '864160641823734378b69da7aa28477771e125af66cf47d5f0f7c8233ef1837f  /tmp/hblock' | shasum -c   && sudo mv /tmp/hblock /usr/local/bin/hblock   && sudo chown 0:0 /usr/local/bin/hblock   && sudo chmod 755 /usr/local/bin/hblock && hblock;
echo;
echo "Install Sublime";
echo;
sudo rpm -v --import https://download.sublimetext.com/sublimehq-rpm-pub.gpg;
sudo dnf config-manager addrepo --from-repofile=https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo;
echo;
###############COMMENTED OUT FLATPAK BITS AS THEY DONT SEEM TO WORK UNTIL AFTER A REBOOT##########################################
#echo "Install flapak programs";
#echo;
#flatpak update && flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo && flatpak install com.mojang.Minecraft com.notepadqq.Notepadqq com.visualstudio.code io.lmms.LMMS org.musescore.MuseScore com.obsproject.Studio com.uploadedlobster.peek org.kde.minuet net.xmind.XMind org.darktable.Darktable org.kde.krita libresprite pixelorama foliate pdfarranger gpuviewer antimicrox firmware pupgui2 wonderwall com.github.unrud.VideoDownloader Komikku rosegarden io.github.muse_sequencer.Muse -y;
#echo;
echo "Enable all the things";
echo;
sudo systemctl set-default graphical.target && sudo systemctl enable sddm;
echo;
echo "Adding all the needed lines to the Niri config file";
echo;
sudo mkdir -p ~/.config/niri && cp /usr/share/doc/niri/default-config.kdl ~/.config/niri/config.kdl;
echo "spawn-at-startup "qs" "-c" "noctalia-shell"" >> ~/.config/niri/config.kdl;
echo "spawn-at-startup "gsettings" "set" "org.gnome.desktop.interface" "scaling-factor" "1"" >> ~/.config/niri/config.kdl;
echo "spawn-at-startup "gsettings" "set" "org.gnome.desktop.interface" "text-scaling-factor" "1"" >> ~/.config/niri/config.kdl;
echo "spawn-at-startup "wlr-randr" "--output" "eDP-1" "--scale" "1"" >> ~/.config/niri/config.kdl;
echo "spawn-at-startup "xdg-desktop-portal"" >> ~/.config/niri/config.kdl;
echo "spawn-at-startup "xwayland-satellite"" >> ~/.config/niri/config.kdl;
echo "spawn-at-startup "/usr/libexec/polkit-mate-authentication-agent-1"" >> ~/.config/niri/config.kdl;
echo;
echo "Enabling auto-relabel";
echo;
sudo touch /.auto-relabel;
echo;
echo "Relabel set, rebooting in 5 seconds";
sleep 5;
reboot;

